# POST http://localhost:3001/users/
# Content-Type: application/json

# {
#   "email": "test@example.com",
#   "password": "randomstrongpassword123"
# }



POST http://localhost:3001/users/
Content-Type: application/json

{
  "password": "1randomstrongpassword123"
}
